server:
  port: 8001
spring:
  application:
    name:  provider-ticket

eureka:
  instance:
    prefer-ip-address: true   # 注册服务的时候 使用服务ip地址进行注册
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/